name: sunsational
description: "A Weather app with a snappy name."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # API
  dio: ^5.7.0
  built_value: ^8.9.2
  built_value_generator: ^8.9.2
  built_collection: ^5.1.1
  collection: ^1.18.0

  # State Management
  get_it: ^8.0.0
  shared_preferences: ^2.2.2
  provider: ^6.0.5

  # UI
  go_router: ^14.2.8
  flex_color_scheme: ^7.3.1


  build_runner: ^2.4.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

# The following section is specific to Flutter packages.
flutter:

  generate: true
  assets:
    - assets/
    - assets/images/

  uses-material-design: true

